apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavn-deployment
  labels:
    app: mavn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mavn
  template:
    metadata:
      labels:
        app: mavn
    spec:
      containers:
      - name: mavn
        image: moatazxz/hello-world-mvn:lts
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavn-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: mavn
  ports:
    - port: 8080
      targetPort: 8080
