---
- name: Deploy application to Kubernetes

  hosts: localhost
  gather_facts: no
  vars:
    kubeconfig_path: ~/kube_config
    ansible_python_interpreter: /usr/bin/python3.7

  tasks:
    - name: Apply Deployment YAML
      k8s:
        state: present
        src: deployment.yaml
        namespace: default

 
