---
apiVersion: v1
kind: Service
metadata:
  name: mavn-nodeport-service
spec:
  type: NodePort
  selector:
    app: mavn
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
<<<<<<< HEAD
=======

>>>>>>> 70457715e6ab72dde3af9fdf525b0039137bf332
